// generated by "sampctl package generate"

#include "screentoworld.inc"

#define RUN_TESTS

#include <YSI\y_testing>

Test:Compile() { // Just check if everything compiles, functionallity can only be tested ingame
    new Float: X;
    new Float: Y;
    new Float: Z;

    ScreenToWorld(0, 0.0, 0.0, X, Y, Z);
    ScreenToWorldRayCast(0, 0.0, 0.0, 0.0, X, Y, Z);
    WorldToScreen(0, 0.0, 0.0, 0.0, X, Y);
    WorldToScreenCheck(0, 0.0, 0.0, 0.0, X, Y);
}