// generated by "sampctl package generate"

#include "screentoworld.inc"

#define RUN_TESTS

#include <YSI\y_testing>

Test:NoErrors() { // Functionally can only be tested ingame
    new
        Float: X,
        Float: Y,
        Float: Z
    ; // results should be false because playerid 0 isn't connected
    ASSERT(ScreenToWorldEx(0, 0.0, 0.0, 0.0, X, Y, Z) == false); // calls ScreenToWorld
    ASSERT(WorldToScreen(0, 0.0, 0.0, 0.0, X, Y) == false); // both use STW_NormCrossProduct
}